<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.4.4 setup script
 * Date: Thu, 30 Apr 2015 10:58:26 +0200
 */

/* Servers configuration */
$i = 0;

/* Server: UBI_Traffic_Database [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'UBI_Traffic_Database';
$cfg['Servers'][$i]['host'] = 'vm0104.virtues.fi';
$cfg['Servers'][$i]['port'] = '3306';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'smeZSswr46';

/* End of servers configuration */

$cfg['blowfish_secret'] = '5541ee9dc934c2.16183626';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>